# Generated by Django 3.0.5 on 2020-05-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
    ]
